### ISSUE TITLE
env setup issue

### ISSUE THREAD

**Issue by MrAbderrahmane** [elycheikhsmail/oak-sqlite-backend-ready#1]
error: TS2345 [ERROR]: Argument of type '"jwk"' is not assignable to parameter of type '"raw"'.
    "jwk",
    ~~~~~
    at https://deno.land/x/god_crypto@v1.4.9/src/rsa/rsa_wc.ts:55:5
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    ? `${code.open}${str.replace(code.regexp, code.open)}${code.close}`
                         ^
    at run (https://deno.land/std@0.99.0/fmt/colors.ts:69:26)
    at Module.yellow (https://deno.land/std@0.99.0/fmt/colors.ts:166:10)
    at Thread (https://deno.land/x/trex@v1.8.0/commands/run.ts:149:24)
    at async Run (https://deno.land/x/trex@v1.8.0/commands/run.ts:211:11)
    at async Main (https://deno.land/x/trex@v1.8.0/cli.ts:191:6)
    at async https://deno.land/x/trex@v1.8.0/cli.ts:286:24

**Comment by elycheikhsmail** [comment]
in general this kind of errors is du to type check and types changes between deno versions.
please what deno version you are using ? and what is your OS ?
any way you can install dvm (deno module in hosted deno.land/x) - like nvm for node  but for deno -  and install deno version 1.12.1 and test again

**Comment by elycheikhsmail** [comment]
i will write new version of this project

**Comment by elycheikhsmail** [comment]
i create this proj
https://github.com/elycheikhsmail/ROM-Framwork
it allow you to quickly create restapi using oak and mysql
